### ISSUE TITLE
Partial pairs

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [dbuenzli/cmdliner#100]
I'd like a CLI API that supports incomplete / partial `Arg.pair` / `Arg.t3`, etceteras.

That is, given `--sort name,asc` as an example, I'd like to have a default value for `asc`, and allow the user to omit it, providing only `--sort name`!

**Comment by dbuenzli** [comment]
That seems quite a specific desire. I suggest you write your own [argument converter](http://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#VALconv).

**Comment by dbuenzli** [comment]
Btw. in your example I'm almost certain that two options `--sort-by` and `--sort-order` will provide a better user experience. In general it's better to avoid defining complex syntax for option arguments.

**Comment by ELLIOTTCABLE** [comment]
I suppose it is a little special-case!

My use-case wasn't important, it's a project I'm immediately discarding. No worries.

(In my case, the issue was that it's a lexicographic sort, and thus there's *multiple* order/key pairs — and `--sort-by last --sort-order ascending --sort-by first --sort-order ascending` is pretty dang verbose, not to mention that arguments that are *so* order-dependent are also their own form of antipattern — I opted for `--sort last,asc --sort first,asc` or similar, but I don't much love that either. Eh! It's a toy project anyway.)

**Comment by dbuenzli** [comment]
I see, then why not specify the sort as a *list* of keys with optional direction something like

 `--sort KEY[-|+][,KEY[+|-]|...`

double check with what shells think of plus and minus though.
