### ISSUE TITLE
Ability to capture the command line argument consumed by a term

### ISSUE THREAD

**Issue by diml** [dbuenzli/cmdliner#101]
In dune we sometimes print hints suggesting to run another dune command to get more details, such as:

```
$ dune runtest --profile release
<some build error>
Hint: try: dune external-lib-deps --profile release @runtest
```

The hint needs to replicate many of the command line flags that where passed to `dune build` in order to ensure that the behavior is the same, such as `--profile release` in this example. To implement that, we currently reconstruct the command line while parsing the flags that are common to all command. This is tedious and has been the cause of several bugs in the past.

One way to make this simpler would be to provide a function in `Cmdliner.Term` that would capture the part of the command line consumed by a term. For instance:

```
val capture_args : 'a t -> ('a * string list) t
```

Then we could simply wrap our `common` term with this function.

**Comment by dbuenzli** [comment]
Solved in https://github.com/dbuenzli/cmdliner/pull/103 under the final name `Term.with_used_args`. If you can confirm everything's alright I can do a release.

**Comment by diml** [comment]
I had a look and everything looks good to me. A release is welcome :)
