### ISSUE TITLE
Alias `-v` to `--version`

### ISSUE THREAD

**Issue by Schniz** [dbuenzli/cmdliner#112]
There is currently no way to show the version number. Lots of tools alias `-v` to `--version` but I see how `-v` can also be `--verbose`.
I wanted to do it in userland, but while I can return something like

```
`Help((`Pager, None))
```

To show help, I can't return

```
`Version
```

to print the version.

My dirty hack was to map over `Sys.argv` and replace `-v` with `--verbose`, but this is not documented in Cmdliner now.

Is there a better way to do it?

Thanks for your hard work! 🙏

**Comment by dbuenzli** [comment]
> Lots of tools alias `-v` to `--version` but I see how `-v` can also be `--verbose`.

Yes that's the reason why there's no option for that. If you need backward compatibility with a pre-existing interface the way you do it is the right way. If that's a new interface I suggest you do not use `-v` for `--version`.

**Comment by dbuenzli** [comment]
(You can of course also define a `-v` command and print the version yourself)

**Comment by Schniz** [comment]
Thanks for the response!

I still think of whether we can have `type ret` to have a <code>\`Version</code> variant, just like the <code>`Help of ...</code> variant, to reuse the ability from Cmdliner itself, although being very simple to implement

**Comment by dbuenzli** [comment]
I prefer if `Cmdliner` using tools always simply respond to `--version` to output the version and do not invent their own scheme. All these tools:
```
> opam list --depends-on=cmdliner | wc -l 
     222
```
are behaving the same and that's a good thing for the end user.

Really keep `-v` for verbosity that's something you want to be short. Asking for version doesn't really have to be.
