### ISSUE TITLE
later options should override earlier options

### ISSUE THREAD

**Issue by olafhering** [dbuenzli/cmdliner#113]
Issue ocaml/dune#2838 is about repeated `-j N` options. Apparently there can only be one `-j` at a time.

I briefly browsed the docs of cmdliner but could not spot the place where it is stated that a given option can exist only once. Recently I used Pythons argparse, which has an `action=append` knob to optionally create a list for multiple occurrences of an option. Without it, later ones will override earlier ones I think. But then, it is certainly up to the implementation how the `*argv[]` array is parsed.

In my [ocaml-rpm-macros.rpm](https://build.opensuse.org/package/show/devel:languages:ocaml/ocaml-rpm-macros) I would like to use the global rpm `%_smp_mflags`, but allow individual packages to pass additional options to `dune` via another shell variable. In this case parmap needs to run `dune runtest` single-threaded to not overload its build VM with too many processes. With my change the command line would be something like `dune runtest -p parmap -j N -j 1`.
I had to revert this until this issue is resolved in one way or another:  [ocaml-rpm-macros](https://build.opensuse.org/package/rdiff/devel:languages:ocaml/ocaml-rpm-macros?linkrev=base&rev=30)

**Comment by dbuenzli** [comment]
Too much noise in your report to understand what you want, please try to be more concise. But from the title of the issue you can do this with [`opt_all`](https://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#VALopt_all) and take the last element of the resulting list.
