### ISSUE TITLE
Pretty-print errors with cmdliner

### ISSUE THREAD

**Issue by VincentCordobes** [dbuenzli/cmdliner#116]
I would like to customize the error message (putting some colors in it)
Using the `'a ret Term.t` type, it seems like I can only pass a string:

```ocaml
let foo id =
  `Error (false, "some error msg")
  
let foo_cmd =
  Term.(ret(const foo $ id_arg)), Term.info "foo"
```

Is there a way to interact with cmdliner's evaluation to pretty print the error?

**Comment by dbuenzli** [comment]
I guess nothing prevents you of having escape characters in that string.

**Comment by VincentCordobes** [comment]
Yes but I still depend on the default error format of cmdliner, which is: 
```
cmd : the error message
```

Yet I want this:

![Screenshot 2020-02-19 at 21 24 57](https://user-images.githubusercontent.com/7091110/74873377-5f0e6980-535f-11ea-9c06-d965c064f1b3.png)

Currently I print the error myself and exit. I would rather let cmdliner handle the exit status for me—for example returning something like 

```ocaml
`Custom_error "No card found with id %a" pp_id id
```

Is this possible @dbuenzli ?

**Comment by dbuenzli** [comment]
> Yes but I still depend on the default error format of cmdliner, which is:
> 
> ```
> cmd : the error message
> ```

Yes that's the [standard](https://www.gnu.org/prep/standards/standards.html#Errors), it allows to easily attribute errors to tools when they are used in scripts, so it's a good idea not deviate from it.

> Currently I print the error myself and exit.

If you are doing non-standard behaviour that's a good solution. Basically just print your errors as you wish and let your terms return exit codes. You `main` function then simply becomes:

```
open Cmdliner
let main () = Term.exit_status (Term.eval mytool)
```
If you want to reuse `Cmdliner`'s exit codes in your own reporting they live as constants [here](https://erratique.ch/software/cmdliner/doc/Cmdliner.Term.html#exits).
