### ISSUE TITLE
Add an underlined documenation markdown directive

### ISSUE THREAD

**Issue by NathanReb** [dbuenzli/cmdliner#118]
I recently had to overwrite the default synopsis and when I tried to mimic what `Cmdliner` does by default I realized I couldn't because there's no markdown directive for underlined text.

My specific use case would be solved by nested commands so it might not be strong enough of an incentive to add such a directive. I feel like when writing documentation though, it often comes up that I can't refer to positional arguments or options' arguments using the same style as `Cmdliner`'s default. In those cases, a `$(u,<text>)` directive might prove helpful. I might have missed an alternative way to achieve that through variables maybe so please let me know if that's the case.

I'm happy to work on a PR if you feel like that would be a worthy addition!

**Comment by dbuenzli** [comment]
You are looking for `$(i,text)`.

**Comment by dbuenzli** [comment]
(Underlining is a convention, e.g. for typewriters when you don't have an italic font. If you checkout the groff output it's `fi` (font italic) directives for what cmdliner generates for you but they get rendered on most systems as underlined.)
