### ISSUE TITLE
Docs Issue in Chrome: syntax error, consider adding a `;' before

### ISSUE THREAD

**Issue by pjhampton** [dbuenzli/cmdliner#119]
Hey

Awesome project. There seems to be an issue with the docs in chrome where the alot of the code blocks are showing as `syntax error, consider adding a `;' before`. I'm not sure if this is an odig problem or just for this project.

<img width="751" alt="Screenshot 2020-04-10 at 14 05 30" src="https://user-images.githubusercontent.com/8960296/78992982-864e0f80-7b34-11ea-83ea-206e24558d20.png">

This is not an issue in Safari it seems. Just letting you know in case you didn't.

**Comment by dbuenzli** [comment]
Can't see that in Chrome `80.0.3987.163` on macos either on the documentation that is published online at https://erratique.ch/software/cmdliner/doc/Cmdliner.html or in `odig` generated documentation. 

Do you maybe have a browser extension that interferes ?

**Comment by pjhampton** [comment]
Hmm, I have  80.0.3987.163 as well on macos. I only have an ad blocker ext which is weird. It's likely a problem with my computer then. Sorry to bother!

**Comment by pjhampton** [comment]
I see! It's the [reason tools ext](https://github.com/reasonml/reason-tools). That is what was screwing it up. I will opan an issue for them.
