### ISSUE TITLE
Support for introspection

### ISSUE THREAD

**Issue by rixed** [dbuenzli/cmdliner#121]
Suppose a program that is using cmdliner wants to execve itself, or exec another program that's using cmdliner.
Instead of building the command line using mere strings, which is error prone (when the command line is updated one has to remember to also update the execve) that would be nice to be able to deconstruct the various Args to programmatically build a string command line that is free from errors and typos by design.

Sort of, I'm asking for a possibility to reverse cmdline into a command line generator rather than parser. One would call a function with the args and its optional values (as OCaml literals) and obtain an array of strings.

Does that make sense?

**Comment by dbuenzli** [comment]
Not to me on a first read but I may be wrong, feel free to discuss open ideas on https://discuss.ocaml.org/
