### ISSUE TITLE
"vopt" arguments and backwards-compatibility

### ISSUE THREAD

**Issue by aalekseyev** [dbuenzli/cmdliner#125]
Currently arguments with optional values (vopt) have some surprising semantics.

There is a proposal to change it for dune: https://github.com/ocaml/dune/pull/4859.
And I wonder if that change would be welcome here.

To recap the problem, it comes down to the ambiguity of "--foo x": it can be interpreted as a flag "--foo" followed by a positional argument "x", or as an option "--foo" with a value payload "x".

For vopt the current behavior is to treat "x" in "--foo x" as a value payload.
This means that you can't backwards-compatibly add a value payload to an existing flag, since "x" needs to be interpreted as a positional argument for backwards compatibility.

The proposal is to change optional value args to require a glued form: "--foo=x".
This helps with backwards compatibility, but also solves another usability quirk: currently if you want to drop an optional value (change "--foo x" into "--foo"), then you also need to adjust the next positional argument.
So "--foo x y" changes into "--foo -- y" if y is a positional argument.

The downside is that this change itself is not backwards-compatible and it makes it impossible to backwards-compatibly change an existing option to make its value optional. (which is possible today)
One possibility is to support both styles, but that may be tricky to document.

Any thoughts?

**Comment by aalekseyev** [comment]
I made a diagram that shows compatibility relations between the styles.
Here `flag`, `option` and `vopt` are the existing styles and `vopt-glued` is the style proposed in the dune PR.
`option-glued` is simply `option` where only glued style is allowed. This is included on the diagram just to clarify the common syntax.

![vopt](https://user-images.githubusercontent.com/5682294/130225322-ebddc0fd-b4cf-4c08-9ea2-447e34ad349f.png)

**Comment by dbuenzli** [comment]
I didn't understand:

0. Your diagram (sorry, but I honestly appreciate the effort :-).
1. What the surprising semantics is. I'd say the rules are clear.
2. What exactly the proposal is.

If 2. is to force long options to always specify their value after an equal, the answer is definitively a no. 

Regardless of backward compatibility constraints, it's much less convenient for the user to type interactively and a lot of *wildly* used tools don't do that anyways (checkout e.g. `git` or `journalctl`).

But yes command line interfaces are terrible, terribly constraint and their parsing is always on the verge of ambiguity if you want to be nice to users (and you should be). 

In that setting I'm affraid it's not really possible to have a system that is convenient both for users to use and that allows to be evolved later without quirks.

If you want to document the design pitfalls and what are the non-breaking or breaking cli evolutions in the docs: most welcome.

**Comment by dbuenzli** [comment]
I just went a bit on the churn you linked to. There seem to be a lot of collective confusion about the ability to "fix the problem".

Before you try to change the system (which I'd advise against, it's not as if these things were not thought about…) I suggest you have a close look at the docs [here](https://erratique.ch/software/cmdliner/doc/Cmdliner.html#cmdline) which precisely document the rules for users.

But yes, long options with optional values do bring a lot ambiguity in the system and it's better to avoid them if you can. For example you can try to have both an option and an option with a mandatory value, but then you need to talk about which one takes over.

**Comment by aalekseyev** [comment]
Re: 1, To me there are two surprising/undesirable things, and the fact that they are documented doesn't really make them go away.
- the fact that it's impossible to evolve a flag into a vopt in a backwards-compatible way
- the fact that omitting the value of vopt requires adjusting unrelated positional arguments next to it on the command-line

Re: 2, the proposal is to make vopts always specify their value after an equal, (only vopts, not all long options)

> it's not as if these things were not thought about

Yeah, that's why I created an issue, hoping to find out what those thoughts were.
I think I've gotten some of that (perfect backwards-compatibility is a non-goal), thanks for that.
I think I'm still unsure why/if you prefer existing semantics over the proposed ones.

**Comment by dbuenzli** [comment]
> Re: 1, To me there are two surprising/undesirable things, and the fact that they are documented doesn't really make them go away.

As I said it's difficult to please everyone and it's a balancing act, I'm just favouring cli users here. 

That being said I don't think it's utterly *surprising*, the parsing rules the system implements are rather simple for end users (see the docs) and the interposition of `--` when you adjust clis is something you get to learn quite quickly in my opinion (and again is not specific to `cmdliner` based tools).

> Re: 2, the proposal is to make vopts always specify their value after an equal, (only vopts, not all long options)
[...]
> I think I'm still unsure why/if you prefer existing semantics over the proposed ones.

The reason why I linked to the docs is that if you change the system you should try to document the new system for users there. I think if you tried to do so you'd quickly see that it would be pretty bad for them, lots of "if"/"unless" would need to be added. 

I'm definitively against what you propose because it means that users need a priori knowledge about the options to adapt their input syntax accordingly. 

Before writing an option value they need to have in the head whether the option has a default value or not so that they use the right syntax for it. As a user that's definitively not something I want to have to think about. Besides it might even lead to more user confusion when the user is not using the right syntax and errors are reported. 

Please don't.

**Comment by aalekseyev** [comment]
> Before writing an option value they need to have in the head whether the option has a default value or not so that they use the right syntax for it. As a user that's definitively not something I want to have to think about

Ok. That is the dual to the current problem where when passing a vopt without an argument the user needs to know that it's not a flag. I agree both problems are bad and I see you're weighing this side more. Fair enough.

**Comment by dbuenzli** [comment]
> That is the dual to the current problem where when passing a vopt without an argument the user needs to know that it's not a flag.

Yes. Though I wouldn't say both sides are even from an user-interaction point of view. I'm pretty sure the current system is easier to describe and use. In particular providing a uniform syntax for specifying options seems quite important to me.
