### ISSUE TITLE
Term.exit is error-prone when used with `'a result`

### ISSUE THREAD

**Issue by edwintorok** [dbuenzli/cmdliner#130]
`Term.exit` accepts any 'a as a valid result and ignores it.
This is quite error prone, if your "main" function happens to return a result.

For example if I slightly modify the example from the Cmdliner docs, then I get a program that raises no compiler warnings or errors, exits with code 0 without printing anything, and yet it has internally failed with an error:
```ocaml
let revolt () = R.error_msg "Some failure"

let revolt_t = Term.(const revolt $ const ())

let () = Term.exit @@ Term.eval (revolt_t, Term.info "revolt")
```

The fix is to call `Term.term_result`, but it would be nice if this could be enforced at the type level:
```ocaml
let revolt () = R.error_msg "Some failure"

let revolt_t = Term.(const revolt $ const ())

let () = Term.exit @@ Term.eval (Term.term_result revolt_t, Term.info "revolt")
```

## Suggested fix 
I'd suggest adding this function to force the result to be unit:
```ocaml
let exit_unit ?term_err (x : unit Term.result) = Term.exit ?term_err x
```

That will then still compile correctly on the correct program:
```ocaml
let revolt () = R.error_msg "Some failure"

let revolt_t = Term.(const revolt $ const ())

let () = exit_unit @@ Term.eval (Term.term_result revolt_t, Term.info "revolt")
```

But fail with a type error on the one where I've forgotten `term_result`:
```ocaml
let revolt () = R.error_msg "Some failure"

let revolt_t = Term.(const revolt $ const ())

let () = exit_unit @@ Term.eval (revolt_t, Term.info "revolt")
```
```
49 | let () = exit_unit @@ Term.eval (revolt_t, Term.info "revolt")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This expression has type
         ('a, [> Bos_setup.R.msg ] as 'b) Rresult.result Cmdliner.Term.result
           =
           [ `Error of [ `Exn | `Parse | `Term ]
           | `Help
           | `Ok of ('a, 'b) Rresult.result
           | `Version ]
       but an expression was expected of type
         unit Cmdliner.Term.result =
           [ `Error of [ `Exn | `Parse | `Term ]
           | `Help
           | `Ok of unit
           | `Version ]
       Type ('a, 'b) Rresult.result = ('a, 'b) Stdlib.result
       is not compatible with type unit 
       Types for tag `Ok are incompatible
```

I'd suggest to copy the current `Term.exit` to `Term.exit_ignore` and adding a deprecation notice on `Term.exit`.
(although `exit_ignore` would be redundant: you can achieve the same outcome by calling `ignore` explicitly in the application and then calling `exit_unit`, so perhaps just introducing `exit_unit` and deprecating `exit` would be enough?)

Note that `exit_unit` would also be useful in other circumstances where your function would return something other than unit due to a typo/mistake in the code (e.g. a partially applied function if you forgot to supply all arguments, an 'a Lwt.t if you somehow forgot to wrap it in `Lwt_main.run`, etc.), but writing programs that pass `'a result' around is the first time I made this mistake.

**Comment by edwintorok** [comment]
If you agree this is the way to fix it I can send a small PR

**Comment by dbuenzli** [comment]
I agree :–) see https://github.com/dbuenzli/cmdliner/pull/124

**Comment by edwintorok** [comment]
Ah I hadn't noticed that `master` is so far ahead of the latest release. Would be nice to have another release when you consider master to be ready.

**Comment by dbuenzli** [comment]
Yes I hope to do that before the end of the year.
