### ISSUE TITLE
Exit info for `term_err` missing

### ISSUE THREAD

**Issue by edwintorok** [dbuenzli/cmdliner#131]
`default_exits` only documents 0, 124 and 125. However if `Term.term_result` is used then `?(term_err=1)` exit status is also possible.
The number here can change so it can't be part of the `default_exits`, but perhaps a convenience `term_err_exit_info: ?term_err:int -> unit -> exit_info` would be useful to have to make it more easy to define (and not forget about) the `1` exit status.

Also an example in Cmdliner on how to corectly write a small program that returns ` ('a, [ `Msg of string ]) Stdlib.result t ` might be useful.

If you want I can send a small PR to implement this.

**Comment by dbuenzli** [comment]
But what should the description be ? This is going to be application defined.

**Comment by dbuenzli** [comment]
In fact I would rather say that the default of `term_err` is wrong. It should rather be `Term.exit_status_cli_error`. Term errors are supposed to be used to validate more complex cli errors.

**Comment by edwintorok** [comment]
It could also be just whatever error the application has encountered while running, not necessarily a CLI error (e.g. it tried to reacha network resource that went down, etc.). `Term.term_result` causes my application to return exit code of 1.
You are right that the description is application defined. Perhaps just an entry in the documentation showing how to use `term_result` is as far as we can go.

**Comment by edwintorok** [comment]
Here is the example I had in mind. This can also be used to test that the application indeed handles errors by exiting with the desired exit code if a flag is supplied:

```ocaml
let revolt trigger_failure =
  if trigger_failure then Error (`Msg "Failure triggered")
  else Ok ()

let revolt_t =
  let trigger = Arg.(value & flag & info ["fail"] ~doc:"Causes the program to exit with a failure") in
  Term.(const revolt $ trigger)

let () =
  let term_err_info = Term.exit_info ~doc:"on errors (with error message printed to stderr)" 1 in
  let exits = term_err_info :: Term.default_exits in
  Term.exit @@ Term.eval (Term.term_result revolt_t, Term.info "revolt" ~exits)
```

**Comment by dbuenzli** [comment]
> It could also be just whatever error the application has encountered while running, not necessarily a CLI error

The idea was more that this was for CLI errors (cue the fact that you can show the `usage`).  

The current API is an incredible mess around exit codes and evaluation. I think I'll rather deprecate the usage of term errors.

My current direction is rather to: 

1. Let people indicate command line errors with `Term.cli_parse_result`.  
2. Encourage people to write terms that evaluate to exit codes. This means they should handle error reporting themselves before the end of evaluation.

**Comment by dbuenzli** [comment]
So in fact the idea behind `Term` errors was for errors that you didn't want to surface in the function providing the command functionality (e.g. a configuration file error). 

Not sure whether this was a good idea but I may have to keep it around for now.

**Comment by dbuenzli** [comment]
@edwintorok current master has new API around exit and evaluation. See [here](https://erratique.ch/software/cmdliner/doc/Cmdliner/Cmd/index.html#eval). 

In particular:

1. These evaluation functions now return an exit code directly on which you invoke `exit` yourself.
2. In these function the default exit code for `term_error` is `Exit.cli_error`.
3. There are `eval_result` functions for evaluating terms that evaluate to `result` values. In case of error the error message is printed and `Exit.some_error` (123) is reported. This code is now in the set of default exit codes of the `Cmd.info` function.

The idea behind 3. is that this is a generic error to use when you don't want to give precise semantics to errors. If you switch your mind later you can then use low codes with more precise semantics.

I hope this solves, in a different way, your issue. Feel free to comment or open issues about the new API before it hits the release.
