### ISSUE TITLE
Type change for Term.exit

### ISSUE THREAD

**Issue by jonludlam** [dbuenzli/cmdliner#134]
Minor issue - the type of `Term.exit` has changed in the compatibility module. The old one was:

```ocaml
val exit : ?term_err:int -> 'a result -> unit
```
whereas the new one is:
```ocaml
val exit : ?term_err:int -> unit result -> unit
```

**Comment by dbuenzli** [comment]
Yes that's on purpose see https://github.com/dbuenzli/cmdliner/pull/124.

Most people that were returning something (e.g. an `int`) were expecting something and that something didn't happen in practice. 

Simply compose with an `ignore` if that's a problem for you (This will be compatible with earlier cmdliner releases).

**Comment by jonludlam** [comment]
OK, makes sense. I guess I was expecting the compatibility interface to be _exactly_ the same as 1.0.4.

**Comment by dbuenzli** [comment]
I think it's better that way, the worst it can do is to uncover bugs (it already did in my code). 

Btw. it's in the release notes, please check them there a few other things you might have to consider.
