### ISSUE TITLE
exit codes with cmdliner 1.1.0

### ISSUE THREAD

**Issue by hannesm** [dbuenzli/cmdliner#141]
Thanks for this great library. I'm using it in a lot of projects. I'm currently trying to upgrade to the non-deprecated part of 1.1.0.

I have some custom exit codes defined (see client/albatross_client_bistro and command-line/albatross_cli for a full code example https://github.com/roburio/albatross):
```OCaml
type exit_code = Connect_failed | Local_authentication_failed

let exit_code_to_int = function Connect_failed -> 122 | Local_authentication_failed -> 119
```

The variant constructors are returned by the commands, and transformed to the code by exit_code_to_int.

In pre-1.1.0 I used at the top-level:
```OCaml
 match Term.eval_choice default_cmd cmds with
 | `Ok x -> exit (exit_code_to_int x)
 | y -> exit (Term.exit_status_of_result y)
```

Now that `Term.eval_choice` is deprecated, I'd use `Cmd.eval_value` -- bu then the `Term.exit_status_of_result` is no longer provided (it is deprecated, a similar binding `Cmdliner_eval.exit_status_of_result` is not publically available via the API.

My question is whether I need to copy & paste that match manually, or use a deprecated function, or is there another path (with the existing API, or would you be fine to expose the exit_status_of_result)?

**Comment by dbuenzli** [comment]
Why don't you simply shift your `exit_code_to_int` into the term and use `Cmd.eval'` ?

**Comment by hannesm** [comment]
That is a possible solution indeed. Though having a dozen subcommands means I've to add `exit_code_to_int` into each term. Anyways, feel free to close this issue, as you like.

**Comment by dbuenzli** [comment]
Since you were the only person to complain in a year. Let's keep it that way.

**Comment by dbuenzli** [comment]
I guess you moved on and I still think it's better to use the simple eval functions if you use bare exit codes. 

But the situation is a tad annoying if your exits are a bit more complex. For that reason I added `Cmd.eval_value'` in aee2a078. This allows to write for example:

```ocaml
match Cmd.eval_value' cmd with 
| `Ok exit -> exit 
| `Exit c -> My_complex_exit.of_code c
```
