### ISSUE TITLE
Should --help and --version be in Options or Common options section?

### ISSUE THREAD

**Issue by mooreryan** [dbuenzli/cmdliner#143]
Hey, so I noticed something today about `--help` and `--version` and their default sections.  Check it out.  (Sorry if this write up is a bit confusing.)

## Options vs common options docs

I noticed that the `--help` and `--version` options go in with the Common Options section by default, even in programs that don't have subcommands.  I'm not sure if this is intended or not.  Here is a line from the docs about Options vs common options

In the docs you describe Common Options like this: 

> The COMMON OPTIONS section. For programs with multiple commands a section that can be used to gather options common to all commands.

And regular options like this: 

> The OPTIONS section. By default options and flag arguments get listed here.

From reading that, it would seem that `--help` and `--version` should go in Options and not Common options if the program has no subcommands.

## `sdocs` default value

Interestingly, in the docs for `Cmd.info` it says that `sdocs` (ie where standard `--help` and `--version` arguments are listed) does default to `Manpage.s_options`:

https://github.com/dbuenzli/cmdliner/blob/74daf226fbacdd29862a01c85fe37c6595b374bf/src/cmdliner.mli#L623

However, when you look at `Cmd.info` it's this:

https://github.com/dbuenzli/cmdliner/blob/74daf226fbacdd29862a01c85fe37c6595b374bf/src/cmdliner_cmd.ml#L11

And `Cmdliner_info.Cmd.v` is this:

https://github.com/dbuenzli/cmdliner/blob/74daf226fbacdd29862a01c85fe37c6595b374bf/src/cmdliner_info.ml#L179

Which has the `sdocs` default as `Cmdliner_manpage.s_common_options`.

So either the docs for `Cmd.info` saying that `sdocs` defaults to `Manpage.s_options` should instead say `Cmdliner_manpage.s_common_options`, or the code setting the default value of `sdocs` to `Cmdliner_manpage.s_common_options` should set it actually to `Manpage.s_options`.  (I.e., I'm not sure which you want it to be, but they currently don't match.)

**Comment by dbuenzli** [comment]
> So either the docs for `Cmd.info` saying that `sdocs` defaults to `Manpage.s_options` should instead say `Cmdliner_manpage.s_common_options`

Yes that's it, the change occurred in the last release see the [release notes](https://github.com/dbuenzli/cmdliner/blob/master/CHANGES.md#new-cmd-module-and-deprecation-of-the-term-evaluation-interface).

It was changed for the following reasons:

1. In general most programs had to change the previous default. So the default was bad.
2. Even if you have a simple tool with few options these options most of the time get in the way of the docs. They are not really interesting and obscure which interesting options your program really offers. As such it feelt better to directly put them in a `COMMON OPTIONS` section, which you can also read as options commonly understood by cli tools.

**Comment by mooreryan** [comment]
Ah yeah I missed that in the release notes...or rather, I probably saw it but it didn't register at the time.  Your explanation makes sense about having the --help and --version in the common options, thanks.

**Comment by dbuenzli** [comment]
Thanks. I tried to clarify the docs.
