### ISSUE TITLE
Long command/tool name overhides man header

### ISSUE THREAD

**Issue by hernoufM** [dbuenzli/cmdliner#146]
Hello, and thank you for awesome and very useful library. Recently I added support of version **cmdliner.1.1.0** to my tool and I have noticed that when looking up manual for a command with a fairly long name (or just a very long tool name) it overhides a part of the header. Here is an example for tool named ```tool``` and its command named ```very-very-long-command-name```.

![tool](https://user-images.githubusercontent.com/56631369/160314082-05f40220-4bcc-4389-a14b-75784e0a293d.png)

![tool_command](https://user-images.githubusercontent.com/56631369/160314084-6a6eb35e-c671-4e50-9a27-d696b0666f11.png)

**Comment by dbuenzli** [comment]
Well your users likely don't want to type `very-very-long-command-name` so don't do that :–) 

There are always limits to what automated typesetting can do. Unless you have something sensitive to propose, I'm not sure there's anything to do here.

**Comment by hernoufM** [comment]
Actually, part of header starts to overhide the rest when total length of tool, command (and eventually sub-command) names in general takes more then 22 characters, that could happen oftentimes.

**Comment by dbuenzli** [comment]
For these kinds of things I don't work on "coulds" and I have absolutely no time to digg again in how roff works or solves this potential issue.

But if you want to research the problem or have solutions I'm all ears.

**Comment by hernoufM** [comment]
Thank you for being honest :=)
