### ISSUE TITLE
Typo in Getting Started

### ISSUE THREAD

**Issue by Alizter** [dbuenzli/cmdliner#155]
In [Getting Started](https://erratique.ch/software/cmdliner/doc/tutorial.html) there is a typo. This
```ocaml
let cmd = Cmd.v (Cmd.info "revolt") revolt_t
```
should probably be this:
```ocaml
let revolt_cmd = Cmd.v (Cmd.info "revolt") revolt_t
```

**Comment by dbuenzli** [comment]
Thank you this was fixed in 01f29b1b by @pveber. Once again https://github.com/ocaml/odoc/pull/303 would be helpful.
