### ISSUE TITLE
Short-opt parsing with `=`

### ISSUE THREAD

**Issue by anmonteiro** [dbuenzli/cmdliner#157]
I don't know whether this is expected behavior, and I couldn't find it explained in [this docs page](https://erratique.ch/software/cmdliner/doc/cli.html#optargs).

Cmdliner currently parses doesn't special case `=` when parsing short optional arguments. E.g. `./my_program -a=foo` will yield `"=foo"` as the value for `a` in my program. I expected this behavior to be consistent with the long option parsing, which would yield `"foo"` e.g. for `./my_program --long-a=foo`.

**Comment by dbuenzli** [comment]
Yes that's expected. You are in the "Glued to a short name: -oa.out" (aka as [POSIX convention](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap12.html)) case of how to specify a value to an option.
