### ISSUE TITLE
Cmdliner does not complain with strict prefixes of defined option

### ISSUE THREAD

**Issue by fblanqui** [dbuenzli/cmdliner#158]
See https://github.com/Deducteam/lambdapi/issues/841

**Comment by dbuenzli** [comment]
Indeed that's expected behaviour [read the docs](https://erratique.ch/software/cmdliner/doc/cli.html#optargs). Same for command names btw.

(I'm still undecided whether that was a good idea in the first place, but in any case it's now too late to change)
