### ISSUE TITLE
Allowing long options starting with a single dash

### ISSUE THREAD

**Issue by MisterDA** [dbuenzli/cmdliner#165]
Dear maintainer,

I'd like to port a tool using custom options processing loosely based on OCaml's `Stdlib.Arg` to Cmdliner's nicer API. The command line switches used by this libraries are however prefixed with a single dash, even for long options, whereas Cmdliner uses two. Thus, switching to Cmdliner would break all users and scripts using single dash switches.

Could there be a way to support single-dash long options in Cmdliner, maybe alongside double-dash options, to ease transition? 

The problem I foreshadow of course is confusing grouped single-letters options, possibly with arguments, with a single-dash-long-option in the parser.

If not, could you perhaps suggest a possible course of action?
Thank you!

**Comment by dbuenzli** [comment]
This should be a FAQ. It has come up numerous times.

> Could there be a way to support single-dash long options in Cmdliner, maybe alongside double-dash options, to ease transition?

No.

> If not, could you perhaps suggest a possible course of action?

Per-process your `Sys.argv` before giving it to the [evaluation function](https://erratique.ch/software/cmdliner/doc/Cmdliner/Cmd/index.html#eval) of your choice.

**Comment by dbuenzli** [comment]
See discussion and further links in https://github.com/dbuenzli/cmdliner/pull/13
