### ISSUE TITLE
EXIT STATUS section, mention the full command rather than only the sub command. 

### ISSUE THREAD

**Issue by Alizter** [dbuenzli/cmdliner#168]
When printing the doc for the exit code statuses the following is used:
```
`P "$(tname) exits with the following status:"
31
```

There are two issues here:
1. `status` should be `statuses` since there is more than one exit code in most cases.
2. The full command name is not printed, but rather the subcommand. For instance

```man
  EXIT STATUS
         rpc exits with the following status:
```

should rather be

```man
  EXIT STATUS
         dune rpc exits with the following status:
```

**Comment by dbuenzli** [comment]
> 1. `status` should be `statuses` since there is more than one exit code in most cases.

I disagree, using statuses would convey that it is possible to exit with more than one status. You should read the preamble sentence and each case as a declaration.

**Comment by Alizter** [comment]
Then perhaps it should be:
```
         rpc exits with one of the following statuses:
```

**Comment by dbuenzli** [comment]
But then you need to deal with singular and plurals.

**Comment by dbuenzli** [comment]
Well you won't be the person who gets an issue the day a user of the library falls on the case and decides to report it…

**Comment by dbuenzli** [comment]
Regarding 1. I simplified the default `EXIT STATUS` wording to `$(iname) exits with:` which works with both singular and plural.

**Comment by Alizter** [comment]
Thanks!
