### ISSUE TITLE
persistent typo in tutorial

### ISSUE THREAD

**Issue by yongrenjie** [dbuenzli/cmdliner#174]
Hello! Just a quick note: on https://erratique.ch/software/cmdliner/doc/tutorial.html I noticed the third and fourth lines are out of sync:

```ocaml
let cmd = Cmd.v (Cmd.info "revolt") revolt_t
let () = exit (Cmd.eval revolt_cmd)   (* should be cmd *)
```

This was mentioned in #138 and I can see it's been fixed on the source code, but as far as I can tell, the website hasn't been updated to reflect this.

<img width="674" alt="Screenshot 2023-02-03 at 12 13 24" src="https://user-images.githubusercontent.com/22414895/216601114-a8cc182c-e865-4e3d-a84a-3fb72ceeb37b.png">

**Comment by dbuenzli** [comment]
Thanks. I updated the docs on the website.
