### ISSUE TITLE
1.2.0 wasn't actually released

### ISSUE THREAD

**Issue by SnarkBoojum** [dbuenzli/cmdliner#179]
The last tag is 1.1.1, while the home page claims 1.2.0 is the latest version.

**Comment by dbuenzli** [comment]
It is released, the tarballs are [here](https://erratique.ch/software/cmdliner/releases/)

**Comment by nojb** [comment]
Related question: is there a way to discover which commit a release tarball corresponds to? (Perhaps using OPAM?)

**Comment by nojb** [comment]
> There's an associated annoted tag in the repo. But sometimes I forget to push it. (I don't know why git insists on having me to add `--tags` do push them).

Thanks; then 1.2.0 seems to be missing: https://erratique.ch/repos/cmdliner/refs/tags.

**Comment by dbuenzli** [comment]
Well I thought I had pushed it before telling you but surely enough I forgot the `--tags` :-)

**Comment by nojb** [comment]
Thanks!
