### ISSUE TITLE
Term.ret unmappable

### ISSUE THREAD

**Issue by dsheets** [dbuenzli/cmdliner#18]
It seems `Term.ret` is `Term.(app (pure f))` (map) composed with an error coreturn. I'd like just the error coreturn function (`'a ret -> 'a`) without the map so that I can reuse a single argument checking function (returning `'a ret`) with a list term.

**Comment by dsheets** [comment]
E.g. <https://github.com/dsheets/webmaster/blob/master/cli/webmaster_cli.ml#L62> can't be easily mapped over a list of paths because we only have `ret : 'a ret t -> 'a t` and don't have access to the actual `'a ret -> 'a` function that is inside of `ret` but composed with the `Term.t` map.

**Comment by dbuenzli** [comment]
I can't provide you with that going from `'a ret` to ` 'a` has an effect in the applicative functor. See the [implementation](https://github.com/dbuenzli/cmdliner/blob/master/src/cmdliner.ml#L1199-1203). I suspect you are putting yourself in the applicative functor too soon.

**Comment by dbuenzli** [comment]
Closing this. Feel free to reopen if I missed something.
