### ISSUE TITLE
Feature request: Support full-path PAGER on native Windows

### ISSUE THREAD

**Issue by kit-ty-kate** [dbuenzli/cmdliner#185]
Currently setting the `PAGER` environment variable on Windows to the full-path to the binary (e.g. `C:\cygwin64\bin\groff.exe`) does not work as cmdliner uses the `where` cmd.exe command which does not support full-paths unlike `command -v` used on Unix.

Discussed in https://github.com/ocaml/opam/pull/5797

**Comment by dbuenzli** [comment]
So what I'm supposed to do ? First check `Filename.is_relative` on the value and if `false` use `where` ?

**Comment by kit-ty-kate** [comment]
I would personally do something like:
```
if String.equal (Filename.basename value) value then
  Sys.command "where ..."
else if Sys.file_exists value then
  0
else
  1
```
to emulate the `command -v` behaviour but I'm a Windows beginner and I'm not too picky anyway.

**Comment by dbuenzli** [comment]
Tried something. Tell me if it doesn't work.

**Comment by kit-ty-kate** [comment]
I've done some tests:
* Paging now works out of the box in Cygwin terminal (when `Sys.win32 = true`)
* Paging doesn't work out of the box on Cmd and Powershell because `TERM` is not set by default (in which case cmdliner bypass the pager check entirely and always render things in plain text)
* When forcing a non-plain mode (with `--help=pager`) with `PAGER=C:\Cygwin64\bin\less.exe` it works on both Cmd and Powershell
* However there is a slight glitch on Cmd where the UTF8 `…` is not rendered correctly. It displays `ÔÇa` (with `a` underlined, small and above other letters) instead.

**Comment by dbuenzli** [comment]
Thanks for the tests. [5292a8c](https://github.com/dbuenzli/cmdliner/commit/5292a8c500e0771abe9d6de4456072056ee35afd) tweaks the logic to always page on `Sys.win32 = true` and `` `Auto ``.

```
It displays ÔÇa
```
Ô ça j'en sais rien. IIRC I don't think `cmd.exe` actually supports UTF-8 by default. Random [stackexchange answer](https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8).

**Comment by dbuenzli** [comment]
Ah but wait `Sys.win32` is also true on `cygwin` we may want to still have the `TERM` lookup there.

**Comment by kit-ty-kate** [comment]
> Ô ça j'en sais rien. IIRC I don't think `cmd.exe` actually supports UTF-8 by default. Random [stackexchange answer](https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8).

From a discussion with @dra27 this is apparently related to https://github.com/ocaml/ocaml/pull/1408

> Ah but wait `Sys.win32` is also true on `cygwin` we may want to still have the `TERM` lookup there.

I agree

**Comment by dbuenzli** [comment]
Now that Windowzing is all the rage, are we subtle enough ?

**Comment by kit-ty-kate** [comment]
I haven't had time to test cmdliner master, I'll do that right now, give me a second

**Comment by kit-ty-kate** [comment]
So after testing, before and after, paging now works perfectly out of the box with `Cygwin Terminal/bash`, `Windows Terminal/PowerShell` and `Command Prompt/cmd` with cmdliner master (paged by `less` on Cygwin and by `more.com` on Windows Terminal and cmd)

However on both `Windows Terminal/PowerShell` and `Command Prompt/cmd` we do get the weird UTF-8 characters still.
Looking a bit into the matter, executing `chcp 65001` (found both in the above stackexchange and [this stackoverflow thread](https://stackoverflow.com/questions/388490/how-can-i-use-unicode-characters-on-the-windows-command-line)) seems to fix the issue for both cmd and powershell. I'm not sure if there is anything we can do anything in cmdliner while waiting for https://github.com/ocaml/ocaml/pull/1408 but at least opam could add the command in our release announcement.

I think we'd be happy to get a release of cmdliner that we can use before the release of opam 2.2.0~beta3 next week or before 2.2.0~rc1, but it's absolutely not critical so no rush ^^

Sorry for the delay on this.

**Comment by dbuenzli** [comment]
Thanks for feedback. Will do a release, I'm eager to use d203fb40ed8deae97a9 in my code bases.
