### ISSUE TITLE
One character arguments with `--`

### ISSUE THREAD

**Issue by WardBrian** [dbuenzli/cmdliner#197]
I'm looking into porting a tool with existing command line structure to use cmdliner. Unfortunately, the existing tool has an option that is one letter but prefixed with `--`. For backwards compatibility, I would like to keep this.

I am unsure how to do this or if it is possible. I tried using prefixing the argument with `-` and `--` in the names list, but this just lead to `---X` and `----X` as options.

**Comment by WardBrian** [comment]
Found:
https://github.com/dbuenzli/cmdliner/blob/cb235b559e29a063fe3c4fb1a60b444cf70dd402/src/cmdliner_info.ml#L100

I think it would be nice if this avoided adding `--` if `--` was already a prefix of the string. I'd be happy to open a PR if this change of behavior was acceptable.

**Comment by dbuenzli** [comment]
I'd rather not. This will lead to people making non standard clis which brings in more confusion.

In general when trying to port existing non standard cli, the advice is to pre-process `Sys.argv` and give it explicitely as a parameter to `Cmd.eval`. See https://github.com/dbuenzli/cmdliner/issues/154.

So basically look for any `--X` before `--` in `Sys.argv` and transform them into `-X`.

**Comment by WardBrian** [comment]
Thanks, that hadn’t occurred to me but does seem reasonable. It’s not a perfect solution, because the documentation will omit this spelling, but I suppose that’s okay.

I agree with the suggestion in #154 that it may be worth giving something like this a brief mention in the manual? It seems it’s not a totally novel problem, and I did try to search the issue list before opening a new one, but failed to find that older issue

**Comment by dbuenzli** [comment]
> It’s not a perfect solution, because the documentation will omit this spelling, but I suppose that’s okay.

You can add something, like `The deprectated form $(b,--X) is also accepted but discouraged.` in the doc string.

> I agree with the suggestion in #154

#198
