### ISSUE TITLE
Support for OCaml 3.12.1

### ISSUE THREAD

**Issue by avsm** [dbuenzli/cmdliner#22]
It would be useful to maintain OCaml 3.12.1 support (possibly as a patchset over the main distribution) in order to use cmdliner in `opam depext`.  See ocaml/ocaml-travisci-skeleton#28 for more discussion.

**Comment by dbuenzli** [comment]
Is it sufficient to support cmdliner's latest version (0.9.7) or do you need 0.9.6 aswell ? (0.9.5 and before do compile with 3.12.1).
