### ISSUE TITLE
Support for environment variables.

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/cmdliner#23]
Support environment variable extraction and documentation; this seems so obvious I don't know why I didn't think about it before, @AltGr may also be eventually interested by this proposal. Basically this will work like for arguments and will automatically document variables under an `ENVIRONMENT VARIABLES` section (or the one specified in `docs`). 

Tentative signature: 

```ocaml
module Env : 
  type 'a t
  type info
  val info : ?docs:string -> ?doc:string -> string -> info 
  val value : 'a Arg.converter -> 'a -> info -> 'a Term.t 
end
```

Maybe we can eschew the `info` type and have everything in the `value` combinator, I don't remember how these things work. 

The following term combinator should also be added : 

```ocaml
Term.override : 'a Term.t -> by:'a option Term.t -> 'a Term.t
```
Which would lead to code like this: 

```ocaml
let f verbose ... = ... (* our code here is free of any env or arg business *)

open Cmdliner 
let verbose_opt = Arg.(value ...)
let verbose_env = Env.(value ...)
let verbose = Term.(override verbose_opt ~by:verbose_var) 
...
```

One question, should we `exit 1` if a parse error occurs or simply report them on the evaluations' `err` formatter  ? I any cases I think remaining silent is a bad idea for the user. 

Any other thoughts ?

**Comment by samoht** [comment]
I'm very happy to see that feature in `cmdliner`, I use it all the time.

The next step is to be able to read these configuration values from a config file ...

**Comment by dbuenzli** [comment]
@samoht one thing after the other... but we could envision that in the future (most likely via a separate `Cmdliner_config` additional library) since I will also certainly need that at some point. 

Do you (or maybe @avsm) have any thought about the error behaviour ? Actually I would be tempted to `exit 1` in addition to screams on stderr. But a command line tool failing because of a broken environment may be annoying. OTOH program arguments are program arguments. Is there any kind of unixy standard behaviour regarding that ?

**Comment by samoht** [comment]
No particular though: it seems reasonable to have a consistent behaviour between parsing of command-line arguments vs. parsing of environment variables.

**Comment by avsm** [comment]
Agreed.  The environment parsing error should be the same as a parsing error on the command-line if possible.  We just need to be careful to define a suitable convention for environment variables (for a boolean, are `1`, `true`, `TruE`, `yes`, `y` all allowable, or is parsing of builtin types much stricter?).

If overrides like this are available, it would be very useful to have a verbose mode that would explain term selection on `stderr`.  This would make debugging the case where some lax `export` a few shell scripts earlier in the execution chain lead to a `cmdliner` app seemingly doing incorrect parsing of a command-line.

It might also be better to recommend that the priority of overrides is the opposite of the example above. Explicit command-line arguments should always override environment variable selection, I think.

**Comment by dbuenzli** [comment]
> Agreed. The environment parsing error should be the same as a parsing error on the command-line if possible. 

Ok.

>We just need to be careful to define a suitable convention for environment variables (for a boolean, are 1, true, TruE, yes, y all allowable, or is parsing of builtin types much stricter?).

This is a matter of providing the right `Arg.converter` values. Currently `Arg.bool` converts with `bool_of_string` so that won't work. I don't have a strong opinion on that I propose that either:

1. `Arg.bool` should be enhanced to support these forms which means that boolean command line arguments will also be able to use them.
2. We recognize that environment value conventions may be different from command line ones and we can provide a few specialized converters in the `Env` module.  

> If overrides like this are available, it would be very useful to have a verbose mode that would explain term selection on stderr.

I think this will be especially useful whenever we add configuration file support to the mix. I'll think about it however it may entail a larger redesign so it may take longer to get there (it's also not evident API wise). 

> It might also be better to recommend that the priority of overrides is the opposite of the example above. Explicit command-line arguments should always override environment variable selection, I think.

Yes right, I thought it was the converse so that e.g. you could modify an invocation not under your strict control. But in fact this would make your tool a nightmare for script writers/users.  We should see an environment variable as a user defined *default*, that the user may want, from time to time, to explicitly override on the command line.

**Comment by dbuenzli** [comment]
> Yes right, I thought it was the converse so that e.g. you could modify an invocation not under your strict control.

Actually is it always clear-cut ? E.g. you may want `OPAMVERBOSE` to always override anything specified no ?

**Comment by AltGr** [comment]
Indeed, good idea!

Some notes from the OPAM use-case:

> > Yes right, I thought it was the converse so that e.g. you could modify an invocation not under your strict control.

> Actually is it always clear-cut ? E.g. you may want OPAMVERBOSE to always override anything specified no ?

In the general case, I consider the env as changing the default value. This case is a bit weird since it's (since recently) a stacking flag (number of occurences of `-v`, vs OPAMVERBOSE that is an integer). I actually take the max of the two values at the moment...  having `-v` _decrease_ verbosity would be weird. It can be overriden with `--quiet` anyway.

For boolean variables, I use the following conversion:

```ocaml
  match String.lowercase (Sys.getenv v) with
    | "" | "0" | "no" | "false" -> false
    | "1" | "yes" | "true" -> true
    | v -> warning v; true
```

The current behaviour is to warn and go on for bad env. values. But I also did it for backwards compatibility with the much more permissive conversion function that was there before.

**Comment by avsm** [comment]
> In the general case, I consider the env as changing the default value.

Agreed.  Consider how it's handled in `make`, where:

```
export FOO=bar
make FOO=car
```

will override with the most recently supplied value (the command line argument).  I think it would be very surprising if an environment variable ever overrode a command-line.  `OCAMLRUNPARAM` attempts to do this in the compiler with pre/post variants and it's as confusing as it can get.

**Comment by dbuenzli** [comment]
> For boolean variables, I use the following conversion:

Well at least because of `""` is `false` this calls for a specialized converter in `Env` I don't want `--bool-flag=` be treated as `--bool-flag=false`.

> I think it would be very surprising if an environment variable ever overrode a command-line.

Ok.

**Comment by Drup** [comment]
Ping for that one. It would be very useful for functoria/mirage has well.

**Comment by dbuenzli** [comment]
Ok so there's now an implementation in e82fd02842719. It's quite different from the proposal I mentioned earlier on this issue. 

We cannot operate at the level of terms since we need to be able to see if there was an argument on the command line of not for the default value we are trying to override, so we actually need to hook in environment lookup whenever a given command line argument is being looked up and parsed. This means that there is a new optional argument to argument information for specifying an environment variable.

I have updated the documentation online. See: 

* The type [Arg.env](http://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#TYPEenv)
* The updated doc of [info](http://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#VALinfo)
* The high-level documentation for [environment variables](http://erratique.ch/software/cmdliner/doc/Cmdliner.html#envlookup).

Regarding the parsing of environment variables, we use exactly the same parser as the one provided for the command line argument and report an error (mentioning it came from an env var) if a parse error occurs. I have not updated the `Arg.bool` parser which will only parse as `bool_of_string`. However `Arg.flag` and `Arg.flag_all` which do not have a parser read a boolean from the environment variable as specified in the above documentation and hence differently from `Arg.bool`.

I'm ready to make a release but I'd still like to first get feedback from one of you on using this.

**Comment by samoht** [comment]
As mentioned on the commit itself, I think I like that simple design. I'll play a bit with it and report back.

**Comment by dbuenzli** [comment]
Thanks everyone for the overwhelming feedback.
