### ISSUE TITLE
Support for uninterpreted arguments

### ISSUE THREAD

**Issue by dsheets** [dbuenzli/cmdliner#25]
I'd like to make a command that accepts another command name and then a sequence of arguments to be passed to that command like `sudo` or `su -c`. To do this, I believe I need to way to turn off argument parsing and force all arguments after a certain one to be captured as literal strings. Is this possible currently somehow?

**Comment by samoht** [comment]
'opam config exec' does that I think

**Comment by dsheets** [comment]
```
$ opam config exec ls
$
```

```
$ opam config exec ls -la
$
```

so opam has the same problem (and maybe should have an issue), afaict.

**Comment by dbuenzli** [comment]
I see two ways to achieve that: 

* Detect where the command line should be split yourself in `Sys.argv` and use [`Term.eval`](http://erratique.ch/software/cmdliner/doc/Cmdliner.Term.html#VALeval) with an `argv` argument that concerns only your tool. 

* Get all positional arguments using [`pos_all`](http://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#VALpos_all) and rely on the POSIX convention that anything following `--`  it to be treated as positional arugments i.e. instruct your users that the synopsis of the command is `mytool [OPTION]... -- command [OPTION]... ARGS`.

**Comment by dbuenzli** [comment]
Note that in effect your users will still be able to write e.g. `mytool command arg1 arg2` it's just that if they want to be able to give *options* to `command` they will need to introduce a `--`.

**Comment by dsheets** [comment]
Those are both good solutions. Thanks!

**Comment by dsheets** [comment]
In fact, it is even documented to use `--` in opam and I'm just in too much of a hurry to notice it. Sorry for the noise. :-)
