### ISSUE TITLE
Default command synopsis missing with eval_choice

### ISSUE THREAD

**Issue by Gbury** [dbuenzli/cmdliner#28]
When using eval_choice, only the synopsis for calling on commands is printed on the default help page, and not the synopsis of the default command, which does not appear in any help output.
For instance consider the following code:

```ocaml
let default =
  let open Cmdliner in
  let main msg = Printf.printf "%s\n" msg in
  let msg =
    let doc = "Message to print" in
    Arg.(value & pos 0 string "hello world !" & info [] ~docv:"MSG" ~doc)
  in
  Term.(pure main $ msg),
  Term.info "test"

let command =
  Cmdliner.Term.(ret (pure (fun () -> Printf.printf "command called\n"; `Ok ()) $ pure ())),
  Cmdliner.Term.info "call"
;;
match Cmdliner.Term.eval_choice default [command] with
| `Version | `Help | `Error `Parse | `Error `Term | `Error `Exn -> exit 2
| `Ok () -> ()
```

When calling `test --help`, the `MSG` positional argument is listed in the list of positional arguments, but the only synopsis showed is :
```
SYNOPSIS
    test COMMAND ...
```
which is partial since it doesn't show the synopsis for the default command (and thus does not explain where to use the `MSG` positional argument).

I agree it may looks like a strange usage,since to call the default command you have to use `test -- 'this is a message'`. However, using optional arguments (of the `default` term) before the positional ones lets you drop the `--`.  Furthermore, forgetting about optional arguments, I find it better to have `--` in the command line rather than have to use an arbitrary command name to use a tool's default function.

**Comment by dbuenzli** [comment]
Not sure something should be done here. Most of usages of `eval_choices` either have a default argument that shows the help or have a `default` term that is also in the list of choices, i.e. there's a default command.

**Comment by dbuenzli** [comment]
Also as mentioned in [this section](http://erratique.ch/software/cmdliner/doc/Cmdliner#manual) you can still devise your own SYNOPSIS if you are not happy about what `Cmdliner` provides. I'm closing this for now, feel free to continue the discussion if you are not convinced or have links to use cases.
