### ISSUE TITLE
Precise that arguments defined with `pos` and `pos rev:true` can overlap.

### ISSUE THREAD

**Issue by braibant** [dbuenzli/cmdliner#29]
Hi, 

The following piece of code defines a term with two arguments using `pos` and `pos rev:true`. The two arguments can actually match the same command line argument (if there is only one of these). 
Unfortunately, the man page makes it unclear that the command might succeed when applied to only one argument.  

It could be nice to: 
- to make it clear in the doc that `pos` and `pos rev:true` arguments can overlap and have some kind of (visual) warning in the man page. 
- or to get a failure explaining that one required argument is missing. 

```
open Cmdliner

let src =
  Arg.(required
       & pos 0 (some string) None
       & info [] ~docv:"SRC" ~doc:"SRC")

let tgt =
  Arg.(required
       & pos ~rev:true 0 (some string) None
       & info [] ~docv:"TGT" ~doc:"TGT")


let f a b =
  assert (a <> b)

let term = Term.(pure f $ src $ tgt)
let info = Term.info "test"

let () = match Term.eval (term, info) with
    `Error _ -> exit 1
  | _ -> exit 0
```

**Comment by dbuenzli** [comment]
Le jeudi, 23 avril 2015 à 16:48, Thomas Braibant a écrit :
> or to get a failure explaining that one required argument is missing.

I'm more inclined to do this. It seems to me that what you have here is a misdesigned command line, the library should not allow you to specify them.  

However I'm not sure exactly what the exact condition to test is, I guess there are also a lot of things that can go wrong by using the other positional combinators.

So maybe I'll just trust the programmer to do the right thing… Will still have a look at this when I'll make the next release, if you have any ideas, welcome.  

Daniel

**Comment by braibant** [comment]
I perfectly agree that defining such a command line is a mistake, and I would like the library to prevent people from doing this kind of things. 

I will have a look at the other combinators, to see if I can come up with a runtime test for this.

**Comment by dbuenzli** [comment]
More precisely the task should be, given a list of [`arg_info`](https://github.com/dbuenzli/cmdliner/blob/0449df4a6ec9d1678bf4d10ddb7c5ab1259f2807/src/cmdliner.ml#L194-L203) values (those of the term to be evaluated), consider only those arguments that are [positional](https://github.com/dbuenzli/cmdliner/blob/0449df4a6ec9d1678bf4d10ddb7c5ab1259f2807/src/cmdliner.ml#L212) and devise a function that finds an inconsistent specification by analysing they [pos_kind](https://github.com/dbuenzli/cmdliner/blob/0449df4a6ec9d1678bf4d10ddb7c5ab1259f2807/src/cmdliner.ml#L188-L192) and [absence](https://github.com/dbuenzli/cmdliner/blob/0449df4a6ec9d1678bf4d10ddb7c5ab1259f2807/src/cmdliner.ml#L179-L181) values.

**Comment by dbuenzli** [comment]
(and of course we should be able to explain that in a reasonable way in the documentation)

**Comment by dbuenzli** [comment]
Tentative explanation and constraint to check on the set of positional arguments of at term:

1. No position is defined by two different argument value
2. If position `n` is defined. Then all arguments < `n` should be defined. 

Note that for 2. `n` may not be known statically (because of `rev` arguments) and I was thinking that maybe required or not had to be taken into account but I don't believe that this should be the case.

Not sure that the definition is complete though.

**Comment by samoht** [comment]
(vaguely related but it would nice to check that optional arguments don't have the same name as well)

**Comment by dbuenzli** [comment]
@samoht why not. We just need to make sure that all these checks do not affect program startup times too much.

**Comment by dbuenzli** [comment]
Yes All seems mutually exclusive with any other spec. because of constraint 1.

**Comment by braibant** [comment]
https://github.com/braibant/cmdliner/tree/wip/pos-errors (not finished)

I played a bit with a dynamic solution for the issue, and a correct error reporting is a pain. In the end, the new errors that are caught should be reported to the author of the CLI, not to the end user. Besides that, there are some subtle cases like:

```
let a =  Arg.(value & pos 0 (some string)  None & info [])
let b =  Arg.(value & pos 2 (some string) None & info [])
let echo a b = ()
let echo_t = Term.(pure echo $ a $ b)
```
In `echo a b`, the `b` argument is not used which yields an error. However, `echo a` would be a valid invocation. 

In the end, all this could probably be solved by a bit of doc.

**Comment by dbuenzli** [comment]
Thanks for working on this. 

> In the end, the new errors that are caught should be reported to the author of the CLI, not to the end user.

Raise `Invalid_argument` for this. It's a programming error. 

> In echo a b, the b argument is not used which yields an error. However, echo a would be a valid invocation.

Can't you detect this ? In this term condition 2. is not satisfied.

**Comment by dbuenzli** [comment]
@braibant Did you get to something ? Speculating a bit I'd say there are high chances to get a new release sometime between July and mid-August. But that's only speculation.

**Comment by braibant** [comment]
I had much things to do lately and could not work on this, but odds are good that I will have much more time to work on things like this early in July.

**Comment by dbuenzli** [comment]
Ok cool, thanks for the heads up.

**Comment by dbuenzli** [comment]
I added a warning about this in the documentation. In the end it shouldn't be too hard for clients not to go insane over this so I'm closing this.

There's now a new, much saner internal representation for positional argument that would make such a check easier, but I think it would still be a bit expensive to do it during cli parsing. It could be useful for a kind of cmdliner introspection mode though. 

@braibant sorry you had to go through the incredibly confusing internal mess that cmdliner is. I'm gradually trying to improve it.
