### ISSUE TITLE
Pre-formatted paragraphs in documentation

### ISSUE THREAD

**Issue by Gbury** [dbuenzli/cmdliner#30]
It is sometimes useful to introduce pre-formatted paragraphs in documentation, for instance to insert fragments of text files, or to have text figures as illustrations (as is done in the `git merge` man page to explain branches).
The main point is that there are some cases where you want to have the ability to print multiple spaces, or to insert a new line in the documentation, in order to precisely control what is printed.
I think that adding a new type of paragraphs to the `Manpage.block` type, such that text in it is printed directly without other formatting would be the simplest way to achieve that.

**Comment by dbuenzli** [comment]
That's a good idea. We could add a `` `Pre of string`` case. Could you help me to track the right `groff` invocations ? A quick search doesn't reveal an obvious command.

**Comment by Gbury** [comment]
After a bit of reading, I think that inserting manual breaks (i.e `.br` requests) after each newline characters should do it. If that is not sufficient (in some strange case), enclosing the text with the `.nf` and `.fi` requests in order to disable filling and adjusting might also help (see http://web.cecs.pdx.edu/~trent/gnu/groff/groff.html#SEC60).
We might also want to add a bit of spacing between these paragraphs and others, using the `\x` escape, though it requires to put another character after it (like a space) in order to have the desired result. You might want to look at http://web.cecs.pdx.edu/~trent/gnu/groff/groff.html#SEC62 for some more information.
For instance, you can draw a square with a diagonal with the following code:
```groff
This is some text, the figure begins afterwards.
\x'10p \" notice the space after the escape sequence
.br
\-\-\-\-\-
.br
|  /|
.br
| / |
.br
|/  |
.br
\-\-\-\-\-
\x'10p \" here also
.br
Normal text resumes here.
```
Another simpler option is to start all lines in the paragraph with a space, which automatically introduces a break, but that would also indent the paragraph. Does it help ?

**Comment by dbuenzli** [comment]
Thanks very much ! Will speed up things when I get to implement this sometime this summer. I also just had a look at the `git-merge` page these `.nf` and `.fi` things are definitively here.

**Comment by Gbury** [comment]
Indeed, contrary to what i just said, you don't need the manual breaks when you use `.nf` and `.fi`, so those should be enough (and exactly what it needed).
