### ISSUE TITLE
Please be compatible with OCaml 3.12

### ISSUE THREAD

**Issue by AltGr** [dbuenzli/cmdliner#31]
We use it in OPAM and keep compat down to 3.12, as it's still widely deployed.
See the patch at https://github.com/ocaml/opam/blob/master/src_ext/patches/cmdliner/backport_pre_4_00_0.patch
(bot note that it will give a deprecation warning on earlier OCaml versions)

Thanks!

**Comment by dbuenzli** [comment]
Ok. So will the next release be (sometimes this summer).
