### ISSUE TITLE
$ Expression Causes Problems with Camlp4

### ISSUE THREAD

**Issue by craig-riecke** [dbuenzli/cmdliner#32]
The $ binary operator is nice, but it causes problems when used with camlp4 extensions.  This is expected, per the OCaml manual (http://caml.inria.fr/pub/docs/manual-ocaml/lex.html).  

-----
Note that the following identifiers are keywords of the Camlp4 extensions and should be avoided for compatibility reasons.

parser    value    $     $$    $:    <:    <<    >>    ??
-----

We currently work around it by using "app" directly but a different binary operator would be more readable.

**Comment by dbuenzli** [comment]
Operators redefinitions should be used sparingly and I'd like to avoid diluting readability by introducing a new synonym. `$` in `cmdliner` has been here for a long time so it is here to stay --- whereas `camlp4` is or should not. 

It seems to me that it's easy enough to define your own operator if you happen to use `camlp4` on the module that defines cmdliner terms.

**Comment by craig-riecke** [comment]
Fair 'nuff. I can live with that workaround.
