### ISSUE TITLE
Clarify doc of eval_peek_opts

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/cmdliner#33]
Explain the result type of the function better.

**Comment by Drup** [comment]
Also, If a parameter is peeked, is it automatically included in the documentation, or do I need to put it in the final term ?

I think it's the former but I assumed the later and get duplicated parameters in documentation.

**Comment by dbuenzli** [comment]
> I think it's the former but I assumed the later and got duplicated parameters in documentation.

Unless I misunderstood what you are saying. I think the problem must be somewhere else. Nothing is recorded (in the sense state being set) when you use `eval_*` functions.
