### ISSUE TITLE
Since building OPAM requires cmdliner, there should be a way to build cmdliner without OPAM

### ISSUE THREAD

**Issue by MSoegtropIMC** [dbuenzli/cmdliner#34]
When configuring OPAM (1.2.2) it outputs:

    checking for OCaml findlib package cmdliner... not found

So building OPAM requires cmdliner, but there doesn't seem to be a way (except manual) to build cmdliner without OPAM. Thsi results in a sort of hen and egg problem.

I think a makefile and if required a configure script should be supplied with all packages required for buildign OPAM itself.

Best regards

Michael

**Comment by MSoegtropIMC** [comment]
P.S.: Some comment describing the command line for ocamlfind would help a lot!

**Comment by samoht** [comment]
See https://github.com/ocaml/opam/blob/master/src_ext/Makefile#L135-L140

**Comment by dbuenzli** [comment]
> P.S.: Some comment describing the command line for ocamlfind would help a lot!

`cmdliner` doesn't depend on `ocamlfind`. The package is very easy to build without `opam` or `ocamlfind`, just follow the package build instruction [here](https://github.com/dbuenzli/cmdliner/blob/1d9fd775b033a709a3436d9ddf57c67d0969921d/opam#L14-L15).  This generate `.install` file at the toplevel of the distribution that you can use for install.

> I think a makefile and if required a configure script

No way.

Given that opam seems to cope well with the current distribution scheme I don't feel anything should be done here.

**Comment by MSoegtropIMC** [comment]
It is the ONLY package required for building opam, which requires manual building and install and the documentation is essentially "figure it out yourself". Of cause one can figure out the syntax and meaning of a .opam file, the likely values of the required parameters, the correct way to install it. But especially for someone new to ocaml, this is much more tedious than necessary. I think 4 lines of documentation would be sufficient:

Build command: "ocaml pkg/build.ml native=true native-dynlink=false"
<Explain what native does>
<Explain what native-dynlinkis does>
Install command: "Not 100% sure what this would be"

Is this really asked to much?

Best regards,
Michael

**Comment by hcarty** [comment]
Doesn't the "opam-full" distribution include all dependencies + build support for them?  I don't think a separate build of cmdliner is required.

**Comment by dbuenzli** [comment]
> But especially for someone new to ocaml, this is much more tedious than necessary.

Someone new to ocaml doesn't build opam by hand. As @hcarty mentions opam has all the support to perform this. 

> I think 4 lines of documentation would be sufficient:
> Build command: "ocaml pkg/build.ml native=true native-dynlink=false"

It is mentioned in the cmdliner's readme to have a look at the opam file for build instructions. This should be sufficient, as soon as you repeat yourself things get out of sync.

> Install command: "Not 100% sure what this would be"

Process the opam `.install` file generated at the root of the distribution. `opam-installer` is one option for this but it may not be applicable in this case.

> Is this really asked to much?

Yes I have other things to do in my life than fiddle with build systems. I don't see what your use case is here especially since `opam` already knows how to do this with the current system.

**Comment by MSoegtropIMC** [comment]
My use case is installing Opam on Cygwin (it works fine now). Regarding the question if opam_full comes with cmdliner / knows how to build it, the opam README contains this info:

* Run `make lib-ext` as advertised by `./configure` if you don't have the
  dependencies installed and only need the opam binary (not the libs). This will
  locally take care of all OCaml dependencies for you.

* Otherwise, make sure to have ocamlfind, ocamlgraph, cmdliner, jsonm, cudf,
  dose 3.2.2+opam and re >= 1.2.0 installed. Or run `opam install
  opam-lib --deps-only` if you already have a working instance. Re-run
  `./configure` once done.

My problem (as an ocaml beginner) is that i simply don't know if I "only need the opam binary (not the libs)". Also this line from the opam readme:

* Run `make libinstall` if needed (this is incompatible with `make lib-ext`, as
  the opam library would conflict with installed versions of the dependencies)

is confusing, How shall I know if I need this or not?

In the end I thought it might be safer to follow the "Otherwise" path cited above and install the dependencies manually. This is fairly painless (takes <30 minutes) except for cmdliner, cause of lack of documentation and methods to build without opam. Building and installing cmdliner took me about 20 minutes (5 times longer than any other dependency). The Opam I got this way works fine on cygwin (so far). 

But I guess the OPAM install instructions are just a bit missleading and one usually does not want "the libs" or to do "make libinstall". I guess in the end one can install the libs using opam, once one has a working opam binary. If this is so, it might help others to add a hint to the opam readme that one usually does not want "the libs" or do "make libinstall" and that the opam created with make lib-ext works perfectly fine.

Or add the 4 lines of documentation to the cmdliner readme I asked for, so that the "Otherwise" path I cited above from the opam readme is less of a nuisance. In the end the opam readme suggests to somehow install cmdliner manually, so there should be some support to do this.

Best regards,

Michael

**Comment by hcarty** [comment]
This discussion should probably be moved to opam's issue tracker, as the proper fix is what you stated: suggest that most users should take the lib-ext approach to building, then install any required libraries (opam's or otherwise) using opam itself.

**Comment by MSoegtropIMC** [comment]
Done. See https://github.com/ocaml/opam/issues/2322.
