### ISSUE TITLE
"Text file busy"

### ISSUE THREAD

**Issue by AltGr** [dbuenzli/cmdliner#37]
It is generally not a problem to remove or overwrite a binary while it is running on Linux: the running program is mapped to the inode, not the filename.

However, when the program is linked with cmdliner, this is no longer possible as I get "Text file busy" errors. I'm guessing it may be due to the man-page handling stuff, and it's just a minor annoyance - I can't `make install` in opam while it's running --, but I was wondering why ?

**Comment by dbuenzli** [comment]
I somehow doubt this is due to anything happening in cmdliner. Man-page generation will only be triggered if you request for help.

**Comment by AltGr** [comment]
Hm, you're right, it's unrelated, the correlation I thought I noticed was just a coincidence. Sorry for the noise!
