### ISSUE TITLE
Custom converters

### ISSUE THREAD

**Issue by rizo** [dbuenzli/cmdliner#40]
Is there a standard way to add new converters?
It doesn't seem to be covered by the documentation.

For now tried to extract some parts from the implementation and come up with this:

```ocaml
let interval_arg : Interval.t Arg.converter =
  ((fun s ->
      try `Ok (Interval.of_string s)
      with Failure _ -> `Error (str "invalid value `%s', interval expected" s)),
   Interval.pp)
```

**Comment by dbuenzli** [comment]
Argument converters are described [here](http://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#argconv) in the documentation.  It may not be in the tutorial but it seems to me that understanding the type of `Arg.converter` is not too involved.
