### ISSUE TITLE
--help, do not default to pager if $TERM is `dumb`

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/cmdliner#43]
[Here](https://github.com/dbuenzli/cmdliner/blob/546baa1765ec4fc3506361a61600034798cd96c6/src/cmdliner.ml#L1336).

See https://github.com/ocaml/opam/issues/2400.

**Comment by dbuenzli** [comment]
Also the pager discover logic should be exposed, I've been c&p the code around and can often be useful for cli tools.

**Comment by mato** [comment]
@dbuenzli You could also use the recently added `Sys.os_type` for this, however that depends on compiler 4.04.0 (see https://github.com/mirage/mirage/issues/660)

**Comment by dbuenzli** [comment]
> @dbuenzli You could also use the recently added Sys.os_type for this, however that depends on compiler 4.04.0 (see mirage/mirage#660)

But I'm not sure what I should be sure what to check for in general. It seems to me that using`TERM` is more in the "test for features" line of things.
