### ISSUE TITLE
Result.result (future Pervasives.result) type

### ISSUE THREAD

**Issue by hcarty** [dbuenzli/cmdliner#45]
Do you have any plans to update cmdliner to use the `Result.result` type in place of the current polymorphic variant for `Ok | Error` handling?  It's a significant backwards-incompatible change.  It also lines up nicely with OCaml >= 4.03.0.

**Comment by dbuenzli** [comment]
I'm undecided, but I tend to think that the amount of breakage this is going to cause may not be worth the change: 
```
> opam list --depopts --depends-on cmdliner | wc -l 
      78
```
There are two things to consider. 

1. There's the term evaluation [result](http://erratique.ch/software/cmdliner/doc/Cmdliner.Term.html#TYPEresult) which if changed is going to break everyone, so I'd rather keep it like this for now, waiting maybe for a larger API break/redesign to change it.
2. There's the type for argument [parsers](http://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#TYPEparser), which if changed may break significantly less code and that I would be more willing to change if people start writing `of_string` functions for their type returning `Rresult.result`s; on the other hand for things you get on the command line these functions are more likely to return options. Note that `Rresult` has [adapters](http://erratique.ch/software/rresult/doc/Rresult.R.html#convert) for both.

If some people are bored and willing to make experiments on the amount of breakage with 2. on the set of dependends please report here.

**Comment by dbuenzli** [comment]
Well actually it's worse than that: 

```
> opam list --rec --depopts --depends-on cmdliner | wc -l 
     225
```

**Comment by dbuenzli** [comment]
I think that for 2. a decent solution would be to switch to `result` in the definition of `'a Arg.converter` and provide a function that transforms current `'a Arg.converter` converters to new ones. This would provide an easy migration path (wrap with a single fun call) for users.

**Comment by hcarty** [comment]
Agreed regarding your suggested fix for 2.

**Comment by dbuenzli** [comment]
Regarding 1., I'm sure it won't be that important to most users once we have #67 which will avoid having people making that bloody pattern match to `exit`. Something I may consider though is at some point provide a better `eval_*` api under an `Eval` module. In that case we might expose the new [internal evaluation result](https://github.com/dbuenzli/cmdliner/blob/b26e145b216563c747233ee2c585c8c9138c4fdf/src/cmdliner.ml#L74-L78) type.

Regarding 2. an upgrade plan is suggested and tracked [here](https://github.com/dbuenzli/cmdliner/issues/55#issuecomment-277846844).
