### ISSUE TITLE
Man page generation is broken w.r.t. to escaping

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/cmdliner#49]
The ["amusing"](http://caml.inria.fr/mantis/view.php?id=6732#c12960) way cmdliner uses `Buffer.add_substitute` is in fact not. In particular the double call means that escaping a `$` is not `$$` but `$$$$`. Not sure if it's not too late to fix this though.

**Comment by fxfactorial** [comment]
Fix would be appreciated.
