### ISSUE TITLE
Make 'a converter abstract and use result type.

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/cmdliner#55]
Before breaking compat introduce a `Arg.converter` constructor.

**Comment by dbuenzli** [comment]
So here's the migration plan. To recall that's what we currently have in `Arg`: 
```ocaml
type 'a parser = string -> [ `Ok of 'a | `Error of string ]
type 'a printer = Format.formatter -> 'a -> unit
type 'a converter = 'a parser * 'a printer
```
in the next release the following two functions will be introduced: 
```ocaml
val converter : ?docv:string -> (string -> ('a, [`Msg of string]) result)) * 'a printer -> 'a converter
val pconverter : ?docv:string -> 'a parser * 'a printer -> 'a converter
```
all cmdliner users will be summoned in the release notes to use one of these two functions (unfortunately there's no warning we can generate). In the next major release the `'a converter` type will be made abstract.

**Comment by hcarty** [comment]
Does this supersede #45 now?  I think it's reasonable to say that it does.

**Comment by dbuenzli** [comment]
Yes, see the comment closure there.

**Comment by dbuenzli** [comment]
Since I want to use the same name as in `bos` which is `'a conv`, I'll do the following slight twist which may help to generate some warning for certain programs (I hope/think).

```ocaml
type 'a conv = 'a parser * 'a printer
val conv : ...
val pconv : ...

type 'a converter = 'a conv 
(** @deprecated Use the {!conv} and {!pconv} constructors. *)
```
