### ISSUE TITLE
Recommended way to group arguments for sublist

### ISSUE THREAD

**Issue by fxfactorial** [dbuenzli/cmdliner#56]
What is the recommend way to subgroup arguments, like how opam does it for `switch`?

**Comment by dbuenzli** [comment]
There's no recommended way. Here are a few examples:

https://github.com/dbuenzli/topkg/blob/9df9e5bd77123ab756a9215ba0ea9ef068ce9f57/src-bin/log.ml
https://github.com/dbuenzli/topkg/blob/9df9e5bd77123ab756a9215ba0ea9ef068ce9f57/src-bin/opam.ml
