### ISSUE TITLE
Recommended way to handle variant positional args?

### ISSUE THREAD

**Issue by rleonid** [dbuenzli/cmdliner#62]
At the moment I have a handy little ETL that takes on the command line different paths to data sources that have different formats:

```
$ tool --fmt1 /one/path --fmt2 /second/path/file.txt
```

I'd like to preserve the order in which these arguments are passed to the program so that my final call would have something akin to `tool [ ('Fmt1, "/one/path"); ('Fmt2, "/second/path/file.txt")]` . At the moment I've resigned myself to adhoc-ly rearranging `Sys.argv` but is there a way to accomplish this with `Cmdliner` ?

Thank you.

**Comment by dbuenzli** [comment]
Not that I'm aware of, but it feels quite an unconventional way of specifiying a `cli`. These `--opt` things are supposed to be *options*.

**Comment by dbuenzli** [comment]
Well actually you could with `Arg.opt_all` and then try to merge with the list of positional args though that would parse a superset. E.g. the following wouldn't error: 

```
/one/path --fmt1 --fmt2 /second/path
```

**Comment by rleonid** [comment]
> These --opt things are supposed to be options. 

Yea, you're right. You can think of this as positional args that need to be converted, or as multiple optional args where we want to know the order of the those args. I'm already using an `opt_all` for each of the `fmt`, `fmt2` ... there are 5 possible formats and each can be repeated as necessary to point to different data source. I guess another option is to use a `vflag_all` for the order but that would be unnecessary. I'm really looking for something like a `vopt_all`.

**Comment by dbuenzli** [comment]
The point is that still remains an odd program to use from a cli convention perpective. 

If there are default formats (i.e. options are really optional) then you should add `--src{1,2,3,4,5}-fmt=FMT` options. 

If it is mandatory to specify the format of sources then you should not use options for that but positional arguments i.e. the synopsis of your cli should be `(FMT SRC)+`. This can be achieved by simply using `Arg.pos_all` and perform the parsing on the resulting list yourself. In case of errors you can still use `Cmdliner`'s erroring mechanism by using `Term.ret`.

**Comment by rleonid** [comment]
True, an odd program. 

You mean`(FMT=SRC)+` options since a `converter` takes one string at a time.

**Comment by dbuenzli** [comment]
> You mean(FMT=SRC)+ options since a converter takes one string at a time.

No, just use a string converter and do the parsing in the lifted function yourself. For example see [this](http://erratique.ch/software/cmdliner/doc/Cmdliner#excp).

**Comment by rleonid** [comment]
Thanks, I think I'll use an `=` in the argument to make the "formatting" assignment explicit.
