### ISSUE TITLE
too many `or` when displaying `Arg.env_var` option

### ISSUE THREAD

**Issue by samoht** [dbuenzli/cmdliner#64]
I just noticed that env options seems to be duplicated if multiple argument names are given:

```
-e or ALCOTEST_SHOW_ERRORS env, --show-errors or ALCOTEST_SHOW_ERRORS
       env
           Display the test errors. Can also be set using the
           ALCOTEST_SHOW_ERRORS env variable
```

Does ` ALCOTEST_SHOW_ERRORS` need to be printed 3 times there? Is there a way to avoid this?

**Comment by dbuenzli** [comment]
> Does ALCOTEST_SHOW_ERRORS need to be printed 3 times there? Is there a way to avoid this?

Yes. You can remove this line https://github.com/mirage/alcotest/pull/83/commits/e735547c2e4c2d8fcb712ede77dc59976948e248#diff-844b2633c72e96b43c76924bbaabb223L483. This will only print it two times. 

The bug seems to only occur with options without arguments.

**Comment by dbuenzli** [comment]
Options without arguments and more than one way of specifiying it which is [not tested](https://github.com/dbuenzli/cmdliner/blob/649a6359ea90f2716be908003f76ddfdecd22505/test/man_test.ml#L8).
