### ISSUE TITLE
Is there for one argument's converter to use the value from another argument?

### ISSUE THREAD

**Issue by ackerleytng** [dbuenzli/cmdliner#83]
Suppose I want to do 

```
./program file config-file.conf
```

Where `config-file.conf` is optional.

If `config-file.conf` is present, the program will use the defined value `config-file.conf`, and if it is not available, I want to use a converter to append `.conf` to the required argument file (hence becoming `file.conf` and then doing a file existence check on `file.conf`. 

This is where the value from argument 1 is required to convert argument 2.

Thanks! (ps: cmdliner is great :))

**Comment by dbuenzli** [comment]
Do two positional arguments one required, one optional and perform the resolution in a lifted function, possibly using `Term.ret` to handle errors as needed in your lifted function. The `cp` [example](http://erratique.ch/software/cmdliner/doc/Cmdliner.html#excp) in the documentation does that kind of thing.
