### ISSUE TITLE
Implement a topkg and .install free build and install procedure

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/cmdliner#86]
This is needed to bootstrap `opam` on debian.

/cc @hendriktews

**Comment by dbuenzli** [comment]
@hendriktews, I did something in 58e5b06bfec17bc649995b785b4017dbd1a971d8. 

Could you please confirm me that this works for you/is enough (e.g. you can do `cd /tmp && opam source --dev cmdliner`). See the `Makefile`.

**Comment by hendriktews** [comment]
Great. From my point of view you can close this issue. It would be helpful if you could release this, because I could then update the Debian cmdliner package.

**Comment by dbuenzli** [comment]
Thanks  ! See https://github.com/ocaml/opam-repository/pull/10009 or http://erratique.ch/software/cmdliner if you only need the tarball.
