### ISSUE TITLE
$(i,Hello world) doesn't underline the space

### ISSUE THREAD

**Issue by cfcs** [dbuenzli/cmdliner#89]
Hi! This is not so much a bug report as it is a question regarding correct usage of `cmdliner`:
Should I in general refrain from using spaces in highlighted items, is this a technical limitation of manpages, or is my system configured incorrectly?

I'm trying to make my help page look better. I read in an issue here that I am supposed to put arguments in italics. In my system/terminal that turns out to be underlining instead of actual italics, but nevertheless it looks a bit odd that the underlining is missing.

I checked the gpg2 man page and it seems that they either use dashes (`quick-revoke-uid user-id user-id-to-remove`) or underscores (`--change-passphrase user_id`). The underlining is also missing for `=`, in `--import-filter name=expr`. So this could easily be the terminal (or manpage/groff/whatever parser) I'm using that has some quirk.

BTW, thanks for supporting manpages in your library. Last time I had to manually write one I was very close to crying at the end of the day.

**Comment by dbuenzli** [comment]
I have no idea.
