### ISSUE TITLE
Referring to arguments in documentation.

### ISSUE THREAD

**Issue by rleonid** [dbuenzli/cmdliner#91]
Apologies if this is mentioned in the documentation, but what is the recommended way to consistently refer to arguments in documentation?

For example if I have a flag --do-it-this-way, I usually define a variable with value "do-it-this-way" and then `sprintf` it into the documentation (such as in an examples or doc of another argument). This is a bit tedious and I wonder if cmdliner supports a better pattern?

**Comment by dbuenzli** [comment]
In the doc of an option itself you can use `$(opt)` as mentioned [here](http://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#VALinfo). Other than there's nothing else you can do. There was a [plan](https://github.com/dbuenzli/cmdliner/issues/42#issuecomment-277513391) for this but TBH I find that a bit overkill.

**Comment by rleonid** [comment]
I see, the plan looks good to me and would be useful to me. As has this library in general, so thank you!
