### ISSUE TITLE
Separate documentation and code logic

### ISSUE THREAD

**Issue by diml** [dbuenzli/cmdliner#93]
Hi,

First of all thanks for cmdliner, it really makes it easy to create nice command line interfaces :)

One thing I have noticed though, is that writing the documentation in OCaml strings is not very convenient as the code base starts to grow:

- the code ends up being interspersed by big documentation strings and it's harder to see the overall logic
- it's hard to imagine the final result such as what the man page will look like when writing the documentation
- we don't get good editor support for writing the documentation, such as syntax highlighting

So my request is to be able to write the parsing code on one side using the applicative interface but without all the documentation and have all the documentation written in a nicer format. Then the system would check that the two are consistent.

For instance, looking at [md2man](https://github.com/sunaku/md2man), [the example](https://raw.githubusercontent.com/sunaku/md2man/master/EXAMPLE.markdown) looks like a much nicer way to write the documentation.

**Comment by dbuenzli** [comment]
> the code ends up being interspersed by big documentation strings and it's harder to see the overall logic

I don't really buy this argument, you have variables in your programming language. These doc strings can perfectly be kept separate from the logic and even centralized in a single module.

> it's hard to imagine the final result such as what the man page will look like when writing the documentation

That problem will remain if you want to keep what `cmdliner` automatically does for you. Somehow if you organise your code well you can still get a good idea of what it will look like modulo the insertions automatically done by cmdliner.

> So my request is to be able to write the parsing code on one side using the applicative interface but without all the documentation and have all the documentation written in a nicer format.

OCaml strings might not be the best place to write documentation but as it stands it seems the simplest and adding more dependencies to `cmdliner` is excluded. It works reasonably well for small to medium cli tools which is (say) 95% of the uses cases. A way to specify pure `groff` fragments could be provided (which your build system would produce) but I'm not sure it's worth the effort. Note that nothing prevents you from having your build system generate the doc strings. I would rather not have a scheme that relies on external files. 

What I have learned is that for larger projects (e.g. w.r.t. `topkg`'s documentation disaster where documentation exists but is spread over API docs strings, API doc manual, an manpages), man pages are ill suited and should be kept to a minimal and quickly redirect to a single, centralized, ***www linkable*** and more user friendly documentation format (i.e. an HTML manual). `odoc`'s recent manual support seems a good place to put your documentation effort as this will also make your manual `odig`able and cross-linked to a potential API.

**Comment by diml** [comment]
> I don't really buy this argument, you have variables in your programming language. These doc strings can perfectly be kept separate from the logic and even centralized in a single module.

Variables? What's that?

More seriously, it's just that you end up with more copies of the same information. For instance for a `--verbose` you'd write:

- `let verbose = Arg.(... & info ["verbose"] ~doc:Doc.verbose)`
- `let verbose = "..."` in `doc.ml`
- `val verbose : string` in `doc.mli`

That's `verbose` written 5 times. But maybe I can just have an overlay for `info` that will lookup the doc automatically based on the argument name.

> odoc's recent manual support seems a good place to put your documentation effort as this will also make your manual odigable and cross-linked to a potential API.

I'll have a look

**Comment by dbuenzli** [comment]
> But maybe I can just have an overlay for info that will lookup the doc automatically based on the argument name.

That seems like a reasonable solution in your case. Note that one advantage of the current scheme is that documentation is also compositional, APIs can export cmdliner terms whose documentation automatically adds to yours. An example of this is `Logs`'s cmdliner support
[here](http://erratique.ch/software/logs/doc/Logs_cli.html).

**Comment by diml** [comment]
I tried this idea and it seems to work quite well: https://github.com/ocaml/dune/pull/519.

I write the command line options documentation in a plain `common.txt` text file:

```
-j JOBS
Run no more than $(i,JOBS) commands simultaneously.

--only-packages PACKAGES
Ignore stanzas referring to a package that is not in $(b,PACKAGES).
$(b,PACKAGES) is a comma-separated list of package names.  Note that
this has the same effect as deleting the relevant stanzas from jbuild
files. It is mostly meant for releases.  During development, it is
likely that what you want instead is to build a particular
$(b,<package>.install) target.

--force, -f
Force actions associated to aliases to be re-executed even if their
dependencies haven't changed.

...
```

then I have a small tool that generates the `Arg.info` values from this file. In the end the parsing code looks like this:

```ocaml  let concurrency =
let module I = Arg_info.Common(struct let docs = Some "COMMON OPTIONS" end) in
let concurrency =
  Arg.(value
       & opt (some int) None
       & I.j)
in
let only_packages =
  Arg.(value
       & opt (some string) None
       & I.only_packages)
in
let force =
  Arg.(value
       & flag
       & I.force)
in
...
```

**Comment by dbuenzli** [comment]
I remain unconvinced by this approach and apparently you can have it without specific support from cmdliner so I'm closing this.
