### ISSUE TITLE
force manpage title to use lowercase name

### ISSUE THREAD

**Issue by jonsterling** [dbuenzli/cmdliner#97]
Hi! Thank you for this cool library. I am wondering if there is a way to force the generated manpage to not capitalize the title of my program in its header and footer; the name of my program is meant to appear in lowercase. Does this sound possible?

**Comment by dbuenzli** [comment]
I'm afraid that's not possible.

**Comment by jonsterling** [comment]
@dbuenzli Thanks for your prompt response! If this sounds like a feature that would be generally undesirable, then feel free to close my ticket.

**Comment by dbuenzli** [comment]
It's not undesirable but everything is a design trade-off, allowing to provide control over the title of the manpage seems of little interest in practice and would clutter the API for little returns in my opinion. 

We could discuss the default which is to capitalize but it would be as arbitrary as not capitalizing (I guess at the time I looked into a few manpage and extracted the pattern from what I saw, see e.g. `man git`).
