### ISSUE TITLE
Publishing to npm, for usage thru BuckleScript / ReasonML

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [dbuenzli/cmdliner#99]
Just letting you know that your library compiles to JS cleanly (well, save a few irrelevant warnings about missing primitives, and [lack of support for `file`/`dir`](https://github.com/ELLIOTTCABLE/bs-cmdliner/issues/1)). Given the ISC license, I didn't think you'd mind me pushing a [basically-unmodified](https://github.com/dbuenzli/cmdliner/compare/452760...ELLIOTTCABLE:master) fork to npm. I scoped it as [`@elliottcable/bs-cmdliner`](https://www.npmjs.com/package/@elliottcable/bs-cmdliner); so if you wish to merge the addition of the BS-configuration upstream and publish it yourself, the name `bs-cmdliner` is still available. ☺️

**Comment by dbuenzli** [comment]
Ok thanks.
